import type { Metadata } from "next";
import {
  Allura,
  Inter,
  Monsieur_La_Doulaise,
  Pinyon_Script,
  Tangerine,
} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const allura = Allura({
  weight: "400",
  variable: "--font-allura",
  display: "swap",
  subsets: ["latin"],
});

const monsieur = Monsieur_La_Doulaise({
  weight: "400",
  variable: "--font-monsieur-la-doulaise",
  display: "swap",
  subsets: ["latin"],
});

const pinyon = Pinyon_Script({
  weight: "400",
  variable: "--font-pinyon-script",
  display: "swap",
  subsets: ["latin"],
});
const tangerine = Tangerine({
  weight: "400",
  variable: "--font-tangerine",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "saltandpeps",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${monsieur.variable} ${pinyon.variable} ${allura.variable} ${tangerine.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
